# Generated by Django 6.0.6 on 2026-06-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_brand_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='models_number',
            new_name='manufacturer_part_number',
        ),
    ]
