# Generated by Django 6.0.6 on 2026-06-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_models_number_productvariant_manufacturer_part_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.UniqueConstraint(fields=('parent_id', 'name'), name='unique_parent_sub_attribute'),
        ),
    ]
