# Generated by Django 6.0.6 on 2026-06-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productattribute_unique_parent_sub_attribute'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='productattribute',
            name='unique_parent_sub_attribute',
            constraint=models.UniqueConstraint(fields=('parent_id', 'name'), name='unique_parent_sub_attribute', violation_error_message='Sub-attributes should be unique in each parent-attribute'),
        ),
    ]
