# Generated by Django 6.0.6 on 2026-06-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productattribute_unique_parent_sub_attribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'ordering': ['parent_id']},
        ),
    ]
