# Generated by Django 6.0.6 on 2026-06-29 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_productattribute_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={},
        ),
    ]
