# Generated by Django 6.0.6 on 2026-06-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_productattribute_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attributevalue',
            constraint=models.UniqueConstraint(fields=('product_attribute_id', 'value'), name='unique_product_attribute_id_value'),
        ),
    ]
