# Generated by Django 6.0.6 on 2026-06-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_attributevalue_unique_product_attribute_id_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
