# Generated by Django 6.0.6 on 2026-06-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='manufacturer_part_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
