# Generated by Django 6.0.6 on 2026-06-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_productvariant_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default=None, upload_to='product/product-image/'),
            preserve_default=False,
        ),
    ]
