# Generated by Django 6.0.6 on 2026-06-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
