# Generated by Django 6.0.6 on 2026-06-30 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_category_is_featured_featuredcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FeaturedBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('brand_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
