# Generated by Django 6.0.6 on 2026-06-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_brand_is_featured_featuredbrand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredcategory',
            name='category_id',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='FeaturedBrand',
        ),
        migrations.DeleteModel(
            name='FeaturedCategory',
        ),
    ]
