# Generated by Django 6.0.6 on 2026-06-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_featuredcategory_category_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['is_featured'], name='idx_featured_brands'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_featured'], name='idx_featured_categories'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['is_featured'], name='idx_featured_product_variant'),
        ),
    ]
