# Generated by Django 6.0.6 on 2026-06-30 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_brand_idx_featured_brands_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_variant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.productvariant'),
        ),
    ]
