# Generated by Django 6.0.6 on 2026-06-29 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0003_cartitem_product_variant_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OP', 'OPEN'), ('PP', 'PAYMENT_PENDING'), ('CN', 'CANCELLED'), ('CM', 'COMPLETED')], default='OP', max_length=2)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('shipping_address', models.CharField(max_length=255)),
                ('payment_provider', models.CharField(choices=[('S', 'STRIPE')], default='S', max_length=1)),
                ('payment_intent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_sesison_id', models.CharField(blank=True, max_length=100, null=True)),
                ('checkout_items', models.JSONField(default=list)),
                ('cart_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cart')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
