# Generated by Django 6.0.6 on 2026-06-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='user_profile_id',
            field=models.ManyToManyField(related_name='addresses', to='authentication.userprofile'),
        ),
    ]
