# Generated by Django 6.0.6 on 2026-06-28 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_address_user_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='user_profile_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.userprofile'),
        ),
    ]
