# Generated by Django 6.0.6 on 2026-06-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('A', 'ACTIVE'), ('C', 'CONVERTED')], default='A', max_length=1),
        ),
    ]
