# Generated by Django 6.0.6 on 2026-06-29 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_status'),
        ('product', '0017_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_variant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productvariant'),
        ),
    ]
