# Generated by Django 6.0.6 on 2026-07-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_grand_total_alter_cartitem_line_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
