# Generated by Django 6.0.6 on 2026-07-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_grand_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Unit price at purchase period', max_digits=8),
        ),
    ]
