# Generated by Django 6.0.6 on 2026-06-29 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipping_address', models.CharField(max_length=255)),
                ('payment_method', models.CharField(choices=[('O', 'ONLINE')], default='O', max_length=1)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('PE', 'PENDING'), ('PA', 'PAID'), ('PR', 'PROCESSING'), ('CN', 'CANCELLED'), ('DE', 'DELIVERED')], default='PE', max_length=2)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('checkout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.checkout')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_variant_name', models.CharField(max_length=255)),
                ('manufacturer_part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
