# Generated by Django 6.0.6 on 2026-06-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_line_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
